// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Direcciones
    {
        public int? Idinstituto { get; set; }
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public DateTime? Fecrea { get; set; }
        public string Usercrea { get; set; }
    }
}