// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace orangebackend6.Models
{
    public partial class ObtenerModulosResult
    {
        public int? permisos { get; set; }
        public int? order_mod { get; set; }
        public string cod_user { get; set; }
        public int? id { get; set; }
        public string moduleName { get; set; }
        public string moduleDescription { get; set; }
        public string icon { get; set; }
        public string color { get; set; }
    }
}
