// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Perfil
    {
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Observacion { get; set; }
        public string Email { get; set; }
        public string Alias { get; set; }
        public string Codpais { get; set; }
        public string Codprov { get; set; }
        public string Coduser { get; set; }
        public string FotoperfilA { get; set; }
        public string FotoperfilB { get; set; }
        public string FotoperfilC { get; set; }
        public string Celular { get; set; }
        public int? Edad { get; set; }
        public string Ciudad { get; set; }
    }
}